DOCKER_REPOSITORY_ORG = zomato
DOCKER_REPOSITORY_NAME = protoc-gen
VERSION_TAG = v1.1

build:
	@echo "Building ${DOCKER_REPOSITORY_ORG}/${DOCKER_REPOSITORY_NAME} docker image"
	docker build -t ${DOCKER_REPOSITORY_ORG}/${DOCKER_REPOSITORY_NAME}:latest -f ./Dockerfile .

push:
	docker build -t ${DOCKER_REPOSITORY_ORG}/${DOCKER_REPOSITORY_NAME}:${VERSION_TAG} -t ${DOCKER_REPOSITORY_ORG}/${DOCKER_REPOSITORY_NAME}:latest ./Dockerfile .
	docker push ${DOCKER_REPOSITORY_ORG}/${DOCKER_REPOSITORY_NAME}:${VERSION_TAG}
	docker push ${DOCKER_REPOSITORY_ORG}/${DOCKER_REPOSITORY_NAME}:latest
